name: Deployment pipeline

on:
  push:
    branches:
      - master

env:
  ARGOCD_VERSION: v2.1.6
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  prepare:
    name: Get ArgoCD cli
    runs-on: ubuntu-20.04  
    steps:
      - name: Install ArgoCD CLI
        id: install_argocd
        shell: bash
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ env.ARGOCD_VERSION }}/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd